const res = {
    results: [
        {
            idEvent: "2069985",
            idAPIfootball: "1208170",
            strEvent: "Manchester United vs Nottingham Forest",
            strEventAlternate: "Nottingham Forest @ Manchester United",
            strFilename:
                "English Premier League 2024-12-07 Manchester United vs Nottingham Forest",
            strSport: "Soccer",
            idLeague: "4328",
            strLeague: "English Premier League",
            strLeagueBadge:
                "https://www.thesportsdb.com/images/media/league/badge/dsnjpz1679951317.png",
            strSeason: "2024-2025",
            strDescriptionEN: "",
            strHomeTeam: "Manchester United",
            strAwayTeam: "Nottingham Forest",
            intHomeScore: "2",
            intRound: "15",
            intAwayScore: "3",
            intSpectators: null,
            strOfficial: "",
            strTimestamp: "2024-12-07T17:30:00",
            dateEvent: "2024-12-07",
            dateEventLocal: "2024-12-07",
            strTime: "17:30:00",
            strTimeLocal: "17:30:00",
            strGroup: "",
            idHomeTeam: "133612",
            strHomeTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/xzqdr11517660252.png",
            idAwayTeam: "133720",
            strAwayTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/bk4qjs1546440351.png",
            intScore: null,
            intScoreVotes: null,
            strResult: "",
            idVenue: "18332",
            strVenue: "Old Trafford",
            strCountry: "England",
            strCity: "",
            strPoster:
                "https://www.thesportsdb.com/images/media/event/poster/jvhwkn1718956073.jpg",
            strSquare:
                "https://www.thesportsdb.com/images/media/event/square/yctab41718955516.jpg",
            strFanart: null,
            strThumb:
                "https://www.thesportsdb.com/images/media/event/thumb/a8t5jv1718955095.jpg",
            strBanner:
                "https://www.thesportsdb.com/images/media/event/banner/u4zxi91718956442.jpg",
            strMap: null,
            strTweet1: "",
            strTweet2: "",
            strTweet3: "",
            strVideo: "https://www.youtube.com/watch?v=2CF0UEa5QnI",
            strStatus: "Match Finished",
            strPostponed: "no",
            strLocked: "unlocked",
        },
        {
            idEvent: "2069963",
            idAPIfootball: "1208148",
            strEvent: "Manchester United vs Everton",
            strEventAlternate: "Everton @ Manchester United",
            strFilename:
                "English Premier League 2024-12-01 Manchester United vs Everton",
            strSport: "Soccer",
            idLeague: "4328",
            strLeague: "English Premier League",
            strLeagueBadge:
                "https://www.thesportsdb.com/images/media/league/badge/dsnjpz1679951317.png",
            strSeason: "2024-2025",
            strDescriptionEN: "",
            strHomeTeam: "Manchester United",
            strAwayTeam: "Everton",
            intHomeScore: "4",
            intRound: "13",
            intAwayScore: "0",
            intSpectators: null,
            strOfficial: "",
            strTimestamp: "2024-12-01T13:30:00",
            dateEvent: "2024-12-01",
            dateEventLocal: "2024-12-01",
            strTime: "13:30:00",
            strTimeLocal: "13:30:00",
            strGroup: "",
            idHomeTeam: "133612",
            strHomeTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/xzqdr11517660252.png",
            idAwayTeam: "133615",
            strAwayTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/eqayrf1523184794.png",
            intScore: null,
            intScoreVotes: null,
            strResult: "",
            idVenue: "18332",
            strVenue: "Old Trafford",
            strCountry: "England",
            strCity: "",
            strPoster:
                "https://www.thesportsdb.com/images/media/event/poster/krl1if1718956067.jpg",
            strSquare:
                "https://www.thesportsdb.com/images/media/event/square/lj77hd1718955509.jpg",
            strFanart: null,
            strThumb:
                "https://www.thesportsdb.com/images/media/event/thumb/irhp4d1718955087.jpg",
            strBanner:
                "https://www.thesportsdb.com/images/media/event/banner/9n7uby1718956437.jpg",
            strMap: null,
            strTweet1: "",
            strTweet2: "",
            strTweet3: "",
            strVideo: "https://www.youtube.com/watch?v=XiAAt4hFboA",
            strStatus: "Match Finished",
            strPostponed: "no",
            strLocked: "unlocked",
        },
        {
            idEvent: "2150687",
            idAPIfootball: "1299212",
            strEvent: "Manchester United vs Bodoe/Glimt",
            strEventAlternate: "Bodoe/Glimt @ Manchester United",
            strFilename:
                "UEFA Europa League 2024-11-28 Manchester United vs Bodoe/Glimt",
            strSport: "Soccer",
            idLeague: "4481",
            strLeague: "UEFA Europa League",
            strLeagueBadge:
                "https://www.thesportsdb.com/images/media/league/badge/mlsr7d1718774547.png",
            strSeason: "2024-2025",
            strDescriptionEN: "",
            strHomeTeam: "Manchester United",
            strAwayTeam: "Bodoe/Glimt",
            intHomeScore: "3",
            intRound: "5",
            intAwayScore: "2",
            intSpectators: null,
            strOfficial: "",
            strTimestamp: "2024-11-28T20:00:00",
            dateEvent: "2024-11-28",
            dateEventLocal: "2024-11-28",
            strTime: "20:00:00",
            strTimeLocal: "20:00:00",
            strGroup: "",
            idHomeTeam: "133612",
            strHomeTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/xzqdr11517660252.png",
            idAwayTeam: "135497",
            strAwayTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/uqpwwx1449165943.png",
            intScore: null,
            intScoreVotes: null,
            strResult: "",
            idVenue: "18332",
            strVenue: "Old Trafford",
            strCountry: "England",
            strCity: "",
            strPoster: "",
            strSquare: "",
            strFanart: null,
            strThumb:
                "https://www.thesportsdb.com/images/media/event/thumb/89r4y71725264819.jpg",
            strBanner: "",
            strMap: null,
            strTweet1: "",
            strTweet2: "",
            strTweet3: "",
            strVideo: "",
            strStatus: "Match Finished",
            strPostponed: "no",
            strLocked: "unlocked",
        },
        {
            idEvent: "2069943",
            idAPIfootball: "1208128",
            strEvent: "Manchester United vs Leicester",
            strEventAlternate: "Leicester @ Manchester United",
            strFilename:
                "English Premier League 2024-11-10 Manchester United vs Leicester",
            strSport: "Soccer",
            idLeague: "4328",
            strLeague: "English Premier League",
            strLeagueBadge:
                "https://www.thesportsdb.com/images/media/league/badge/dsnjpz1679951317.png",
            strSeason: "2024-2025",
            strDescriptionEN: "",
            strHomeTeam: "Manchester United",
            strAwayTeam: "Leicester",
            intHomeScore: "3",
            intRound: "11",
            intAwayScore: "0",
            intSpectators: null,
            strOfficial: "",
            strTimestamp: "2024-11-10T14:00:00",
            dateEvent: "2024-11-10",
            dateEventLocal: "2024-11-10",
            strTime: "14:00:00",
            strTimeLocal: "14:00:00",
            strGroup: "",
            idHomeTeam: "133612",
            strHomeTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/xzqdr11517660252.png",
            idAwayTeam: "133626",
            strAwayTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/xtxwtu1448813356.png",
            intScore: null,
            intScoreVotes: null,
            strResult: "",
            idVenue: "18332",
            strVenue: "Old Trafford",
            strCountry: "England",
            strCity: "",
            strPoster:
                "https://www.thesportsdb.com/images/media/event/poster/my66a81720160914.jpg",
            strSquare:
                "https://www.thesportsdb.com/images/media/event/square/njdmlu1720160933.jpg",
            strFanart: null,
            strThumb:
                "https://www.thesportsdb.com/images/media/event/thumb/hevl9e1720158999.jpg",
            strBanner:
                "https://www.thesportsdb.com/images/media/event/banner/7dyejw1720160953.jpg",
            strMap: null,
            strTweet1: "",
            strTweet2: "",
            strTweet3: "",
            strVideo: "https://www.youtube.com/watch?v=gpeAgyUqmUQ",
            strStatus: "Match Finished",
            strPostponed: "no",
            strLocked: "unlocked",
        },
        {
            idEvent: "2150671",
            idAPIfootball: "1299196",
            strEvent: "Manchester United vs PAOK",
            strEventAlternate: "PAOK @ Manchester United",
            strFilename:
                "UEFA Europa League 2024-11-07 Manchester United vs PAOK",
            strSport: "Soccer",
            idLeague: "4481",
            strLeague: "UEFA Europa League",
            strLeagueBadge:
                "https://www.thesportsdb.com/images/media/league/badge/mlsr7d1718774547.png",
            strSeason: "2024-2025",
            strDescriptionEN: "",
            strHomeTeam: "Manchester United",
            strAwayTeam: "PAOK",
            intHomeScore: "2",
            intRound: "4",
            intAwayScore: "0",
            intSpectators: null,
            strOfficial: "",
            strTimestamp: "2024-11-07T20:00:00",
            dateEvent: "2024-11-07",
            dateEventLocal: "2024-11-07",
            strTime: "20:00:00",
            strTimeLocal: "20:00:00",
            strGroup: "",
            idHomeTeam: "133612",
            strHomeTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/xzqdr11517660252.png",
            idAwayTeam: "133749",
            strAwayTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/m15zsh1602774126.png",
            intScore: null,
            intScoreVotes: null,
            strResult: "",
            idVenue: "18332",
            strVenue: "Old Trafford",
            strCountry: "England",
            strCity: "",
            strPoster: "",
            strSquare: "",
            strFanart: null,
            strThumb:
                "https://www.thesportsdb.com/images/media/event/thumb/f3dt181725264806.jpg",
            strBanner: "",
            strMap: null,
            strTweet1: "",
            strTweet2: "",
            strTweet3: "",
            strVideo: "https://www.youtube.com/watch?v=f2Z1qaUr6eU",
            strStatus: "Match Finished",
            strPostponed: "no",
            strLocked: "unlocked",
        },
    ],
};

const res1 = {
    results: [
        {
            idEvent: "2069992",
            idAPIfootball: "1208177",
            strEvent: "Liverpool vs Fulham",
            strEventAlternate: "Fulham @ Liverpool",
            strFilename:
                "English Premier League 2024-12-14 Liverpool vs Fulham",
            strSport: "Soccer",
            idLeague: "4328",
            strLeague: "English Premier League",
            strLeagueBadge:
                "https://www.thesportsdb.com/images/media/league/badge/dsnjpz1679951317.png",
            strSeason: "2024-2025",
            strDescriptionEN: "",
            strHomeTeam: "Liverpool",
            strAwayTeam: "Fulham",
            intHomeScore: "2",
            intRound: "16",
            intAwayScore: "2",
            intSpectators: null,
            strOfficial: "",
            strTimestamp: "2024-12-14T15:00:00",
            dateEvent: "2024-12-14",
            dateEventLocal: "2024-12-14",
            strTime: "15:00:00",
            strTimeLocal: "15:00:00",
            strGroup: "",
            idHomeTeam: "133602",
            strHomeTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/ar5tn91728915882.png",
            idAwayTeam: "133600",
            strAwayTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/xwwvyt1448811086.png",
            intScore: null,
            intScoreVotes: null,
            strResult: "",
            idVenue: "15407",
            strVenue: "Anfield",
            strCountry: "England",
            strCity: "",
            strPoster:
                "https://www.thesportsdb.com/images/media/event/poster/rah5y01689062682.jpg",
            strSquare:
                "https://www.thesportsdb.com/images/media/event/square/ktpv551689062825.jpg",
            strFanart: null,
            strThumb:
                "https://www.thesportsdb.com/images/media/event/thumb/plvas21689062524.jpg",
            strBanner:
                "https://www.thesportsdb.com/images/media/event/banner/otfbq21689062959.jpg",
            strMap: null,
            strTweet1: "",
            strTweet2: "",
            strTweet3: "",
            strVideo: "https://www.youtube.com/watch?v=f7n99M1ZxI4",
            strStatus: "Match Finished",
            strPostponed: "no",
            strLocked: "unlocked",
        },
        {
            idEvent: "2069962",
            idAPIfootball: "1208147",
            strEvent: "Liverpool vs Manchester City",
            strEventAlternate: "Manchester City @ Liverpool",
            strFilename:
                "English Premier League 2024-12-01 Liverpool vs Manchester City",
            strSport: "Soccer",
            idLeague: "4328",
            strLeague: "English Premier League",
            strLeagueBadge:
                "https://www.thesportsdb.com/images/media/league/badge/dsnjpz1679951317.png",
            strSeason: "2024-2025",
            strDescriptionEN: "",
            strHomeTeam: "Liverpool",
            strAwayTeam: "Manchester City",
            intHomeScore: "2",
            intRound: "13",
            intAwayScore: "0",
            intSpectators: null,
            strOfficial: "",
            strTimestamp: "2024-12-01T16:00:00",
            dateEvent: "2024-12-01",
            dateEventLocal: "2024-12-01",
            strTime: "16:00:00",
            strTimeLocal: "16:00:00",
            strGroup: "",
            idHomeTeam: "133602",
            strHomeTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/ar5tn91728915882.png",
            idAwayTeam: "133613",
            strAwayTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/vwpvry1467462651.png",
            intScore: null,
            intScoreVotes: null,
            strResult: "",
            idVenue: "15407",
            strVenue: "Anfield",
            strCountry: "England",
            strCity: "",
            strPoster:
                "https://www.thesportsdb.com/images/media/event/poster/a3yn5s1718956067.jpg",
            strSquare:
                "https://www.thesportsdb.com/images/media/event/square/pthbzv1718955509.jpg",
            strFanart: null,
            strThumb:
                "https://www.thesportsdb.com/images/media/event/thumb/15i1f61718955086.jpg",
            strBanner:
                "https://www.thesportsdb.com/images/media/event/banner/abdmof1718956437.jpg",
            strMap: null,
            strTweet1: "",
            strTweet2: "",
            strTweet3: "",
            strVideo: "https://www.youtube.com/watch?v=58I8f5iDOpY",
            strStatus: "Match Finished",
            strPostponed: "no",
            strLocked: "unlocked",
        },
        {
            idEvent: "2150427",
            idAPIfootball: "1299071",
            strEvent: "Liverpool vs Real Madrid",
            strEventAlternate: "Real Madrid @ Liverpool",
            strFilename:
                "UEFA Champions League 2024-11-27 Liverpool vs Real Madrid",
            strSport: "Soccer",
            idLeague: "4480",
            strLeague: "UEFA Champions League",
            strLeagueBadge:
                "https://www.thesportsdb.com/images/media/league/badge/5y7gsj1678720262.png",
            strSeason: "2024-2025",
            strDescriptionEN: "",
            strHomeTeam: "Liverpool",
            strAwayTeam: "Real Madrid",
            intHomeScore: "2",
            intRound: "5",
            intAwayScore: "0",
            intSpectators: null,
            strOfficial: "",
            strTimestamp: "2024-11-27T20:00:00",
            dateEvent: "2024-11-27",
            dateEventLocal: "2024-11-27",
            strTime: "20:00:00",
            strTimeLocal: "20:00:00",
            strGroup: "",
            idHomeTeam: "133602",
            strHomeTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/ar5tn91728915882.png",
            idAwayTeam: "133738",
            strAwayTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/vwvwrw1473502969.png",
            intScore: null,
            intScoreVotes: null,
            strResult: "",
            idVenue: "15407",
            strVenue: "Anfield",
            strCountry: "England",
            strCity: "",
            strPoster:
                "https://www.thesportsdb.com/images/media/event/poster/23enz01653760557.jpg",
            strSquare: "",
            strFanart: null,
            strThumb:
                "https://www.thesportsdb.com/images/media/event/thumb/5sc6f21725264630.jpg",
            strBanner: "",
            strMap: null,
            strTweet1: "",
            strTweet2: "",
            strTweet3: "",
            strVideo: "",
            strStatus: "Match Finished",
            strPostponed: "no",
            strLocked: "unlocked",
        },
        {
            idEvent: "2069942",
            idAPIfootball: "1208127",
            strEvent: "Liverpool vs Aston Villa",
            strEventAlternate: "Aston Villa @ Liverpool",
            strFilename:
                "English Premier League 2024-11-09 Liverpool vs Aston Villa",
            strSport: "Soccer",
            idLeague: "4328",
            strLeague: "English Premier League",
            strLeagueBadge:
                "https://www.thesportsdb.com/images/media/league/badge/dsnjpz1679951317.png",
            strSeason: "2024-2025",
            strDescriptionEN: "",
            strHomeTeam: "Liverpool",
            strAwayTeam: "Aston Villa",
            intHomeScore: "2",
            intRound: "11",
            intAwayScore: "0",
            intSpectators: null,
            strOfficial: "",
            strTimestamp: "2024-11-09T20:00:00",
            dateEvent: "2024-11-09",
            dateEventLocal: "2024-11-09",
            strTime: "20:00:00",
            strTimeLocal: "20:00:00",
            strGroup: "",
            idHomeTeam: "133602",
            strHomeTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/ar5tn91728915882.png",
            idAwayTeam: "133601",
            strAwayTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/jykrpv1717309891.png",
            intScore: null,
            intScoreVotes: null,
            strResult: "",
            idVenue: "15407",
            strVenue: "Anfield",
            strCountry: "England",
            strCity: "",
            strPoster:
                "https://www.thesportsdb.com/images/media/event/poster/vghhu11718956061.jpg",
            strSquare:
                "https://www.thesportsdb.com/images/media/event/square/zwsjhe1718955503.jpg",
            strFanart: null,
            strThumb:
                "https://www.thesportsdb.com/images/media/event/thumb/8chjt81718955078.jpg",
            strBanner:
                "https://www.thesportsdb.com/images/media/event/banner/ix8vf51718956433.jpg",
            strMap: null,
            strTweet1: "",
            strTweet2: "",
            strTweet3: "",
            strVideo: "https://www.youtube.com/watch?v=1sFLfFCnGgk",
            strStatus: "Match Finished",
            strPostponed: "no",
            strLocked: "unlocked",
        },
        {
            idEvent: "2150400",
            idAPIfootball: "1299044",
            strEvent: "Liverpool vs Bayer Leverkusen",
            strEventAlternate: "Bayer Leverkusen @ Liverpool",
            strFilename:
                "UEFA Champions League 2024-11-05 Liverpool vs Bayer Leverkusen",
            strSport: "Soccer",
            idLeague: "4480",
            strLeague: "UEFA Champions League",
            strLeagueBadge:
                "https://www.thesportsdb.com/images/media/league/badge/5y7gsj1678720262.png",
            strSeason: "2024-2025",
            strDescriptionEN: "",
            strHomeTeam: "Liverpool",
            strAwayTeam: "Bayer Leverkusen",
            intHomeScore: "4",
            intRound: "4",
            intAwayScore: "0",
            intSpectators: null,
            strOfficial: "",
            strTimestamp: "2024-11-05T20:00:00",
            dateEvent: "2024-11-05",
            dateEventLocal: "2024-11-05",
            strTime: "20:00:00",
            strTimeLocal: "20:00:00",
            strGroup: "",
            idHomeTeam: "133602",
            strHomeTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/ar5tn91728915882.png",
            idAwayTeam: "133666",
            strAwayTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/3x9k851726760113.png",
            intScore: null,
            intScoreVotes: null,
            strResult: "",
            idVenue: "15407",
            strVenue: "Anfield",
            strCountry: "England",
            strCity: "",
            strPoster: "",
            strSquare: "",
            strFanart: null,
            strThumb:
                "https://www.thesportsdb.com/images/media/event/thumb/pc35jm1725264611.jpg",
            strBanner: "",
            strMap: null,
            strTweet1: "",
            strTweet2: "",
            strTweet3: "",
            strVideo: "",
            strStatus: "Match Finished",
            strPostponed: "no",
            strLocked: "unlocked",
        },
    ],
};

const res2 = {
    results: [
        {
            idEvent: "2150578",
            idAPIfootball: "1299386",
            strEvent: "Chelsea vs Shamrock Rovers",
            strEventAlternate: "Shamrock @ Chelsea",
            strFilename:
                "UEFA Conference League 2024-12-19 Chelsea vs Shamrock Rovers",
            strSport: "Soccer",
            idLeague: "5071",
            strLeague: "UEFA Conference League",
            strLeagueBadge:
                "https://www.thesportsdb.com/images/media/league/badge/ymfo5j1718775759.png",
            strSeason: "2024-2025",
            strDescriptionEN: "",
            strHomeTeam: "Chelsea",
            strAwayTeam: "Shamrock",
            intHomeScore: "5",
            intRound: "6",
            intAwayScore: "1",
            intSpectators: null,
            strOfficial: "",
            strTimestamp: "2024-12-19T20:00:00",
            dateEvent: "2024-12-19",
            dateEventLocal: "2024-12-19",
            strTime: "20:00:00",
            strTimeLocal: "20:00:00",
            strGroup: "",
            idHomeTeam: "133610",
            strHomeTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/yvwvtu1448813215.png",
            idAwayTeam: "133978",
            strAwayTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/u1zowj1491504381.png",
            intScore: null,
            intScoreVotes: null,
            strResult: "",
            idVenue: "16126",
            strVenue: "Stamford Bridge",
            strCountry: "England",
            strCity: "",
            strPoster: "",
            strSquare: "",
            strFanart: null,
            strThumb:
                "https://www.thesportsdb.com/images/media/event/thumb/usbft81725264739.jpg",
            strBanner: "",
            strMap: null,
            strTweet1: "",
            strTweet2: "",
            strTweet3: "",
            strVideo: "",
            strStatus: "Match Finished",
            strPostponed: "no",
            strLocked: "unlocked",
        },
        {
            idEvent: "2069991",
            idAPIfootball: "1208176",
            strEvent: "Chelsea vs Brentford",
            strEventAlternate: "Brentford @ Chelsea",
            strFilename:
                "English Premier League 2024-12-15 Chelsea vs Brentford",
            strSport: "Soccer",
            idLeague: "4328",
            strLeague: "English Premier League",
            strLeagueBadge:
                "https://www.thesportsdb.com/images/media/league/badge/dsnjpz1679951317.png",
            strSeason: "2024-2025",
            strDescriptionEN: "",
            strHomeTeam: "Chelsea",
            strAwayTeam: "Brentford",
            intHomeScore: "2",
            intRound: "16",
            intAwayScore: "1",
            intSpectators: null,
            strOfficial: "",
            strTimestamp: "2024-12-15T19:00:00",
            dateEvent: "2024-12-15",
            dateEventLocal: "2024-12-15",
            strTime: "19:00:00",
            strTimeLocal: "19:00:00",
            strGroup: "",
            idHomeTeam: "133610",
            strHomeTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/yvwvtu1448813215.png",
            idAwayTeam: "134355",
            strAwayTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/grv1aw1546453779.png",
            intScore: null,
            intScoreVotes: null,
            strResult: "",
            idVenue: "16126",
            strVenue: "Stamford Bridge",
            strCountry: "England",
            strCity: "",
            strPoster:
                "https://www.thesportsdb.com/images/media/event/poster/zsi7xk1689062666.jpg",
            strSquare:
                "https://www.thesportsdb.com/images/media/event/square/iw9gsa1689062810.jpg",
            strFanart: null,
            strThumb:
                "https://www.thesportsdb.com/images/media/event/thumb/kcg29k1689062505.jpg",
            strBanner:
                "https://www.thesportsdb.com/images/media/event/banner/3dc5571689062946.jpg",
            strMap: null,
            strTweet1: "",
            strTweet2: "",
            strTweet3: "",
            strVideo: "https://www.youtube.com/watch?v=V-VBqhtlDb4",
            strStatus: "Match Finished",
            strPostponed: "no",
            strLocked: "unlocked",
        },
        {
            idEvent: "2069960",
            idAPIfootball: "1208145",
            strEvent: "Chelsea vs Aston Villa",
            strEventAlternate: "Aston Villa @ Chelsea",
            strFilename:
                "English Premier League 2024-12-01 Chelsea vs Aston Villa",
            strSport: "Soccer",
            idLeague: "4328",
            strLeague: "English Premier League",
            strLeagueBadge:
                "https://www.thesportsdb.com/images/media/league/badge/dsnjpz1679951317.png",
            strSeason: "2024-2025",
            strDescriptionEN: "",
            strHomeTeam: "Chelsea",
            strAwayTeam: "Aston Villa",
            intHomeScore: "3",
            intRound: "13",
            intAwayScore: "0",
            intSpectators: null,
            strOfficial: "",
            strTimestamp: "2024-12-01T13:30:00",
            dateEvent: "2024-12-01",
            dateEventLocal: "2024-12-01",
            strTime: "13:30:00",
            strTimeLocal: "13:30:00",
            strGroup: "",
            idHomeTeam: "133610",
            strHomeTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/yvwvtu1448813215.png",
            idAwayTeam: "133601",
            strAwayTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/jykrpv1717309891.png",
            intScore: null,
            intScoreVotes: null,
            strResult: "",
            idVenue: "16126",
            strVenue: "Stamford Bridge",
            strCountry: "England",
            strCity: "",
            strPoster:
                "https://www.thesportsdb.com/images/media/event/poster/7moexc1718956066.jpg",
            strSquare:
                "https://www.thesportsdb.com/images/media/event/square/vpu6t81718955508.jpg",
            strFanart: null,
            strThumb:
                "https://www.thesportsdb.com/images/media/event/thumb/fljb0l1718955085.jpg",
            strBanner:
                "https://www.thesportsdb.com/images/media/event/banner/z81if11718956437.jpg",
            strMap: null,
            strTweet1: "",
            strTweet2: "",
            strTweet3: "",
            strVideo: "https://www.youtube.com/watch?v=RsC6c9UdYSI",
            strStatus: "Match Finished",
            strPostponed: "no",
            strLocked: "unlocked",
        },
        {
            idEvent: "2069940",
            idAPIfootball: "1208125",
            strEvent: "Chelsea vs Arsenal",
            strEventAlternate: "Arsenal @ Chelsea",
            strFilename: "English Premier League 2024-11-10 Chelsea vs Arsenal",
            strSport: "Soccer",
            idLeague: "4328",
            strLeague: "English Premier League",
            strLeagueBadge:
                "https://www.thesportsdb.com/images/media/league/badge/dsnjpz1679951317.png",
            strSeason: "2024-2025",
            strDescriptionEN: "",
            strHomeTeam: "Chelsea",
            strAwayTeam: "Arsenal",
            intHomeScore: "1",
            intRound: "11",
            intAwayScore: "1",
            intSpectators: null,
            strOfficial: "",
            strTimestamp: "2024-11-10T16:30:00",
            dateEvent: "2024-11-10",
            dateEventLocal: "2024-11-10",
            strTime: "16:30:00",
            strTimeLocal: "16:30:00",
            strGroup: "",
            idHomeTeam: "133610",
            strHomeTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/yvwvtu1448813215.png",
            idAwayTeam: "133604",
            strAwayTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/uyhbfe1612467038.png",
            intScore: null,
            intScoreVotes: null,
            strResult: "",
            idVenue: "16126",
            strVenue: "Stamford Bridge",
            strCountry: "England",
            strCity: "",
            strPoster:
                "https://www.thesportsdb.com/images/media/event/poster/zrsf4v1689062662.jpg",
            strSquare:
                "https://www.thesportsdb.com/images/media/event/square/pxm8j41689062806.jpg",
            strFanart: null,
            strThumb:
                "https://www.thesportsdb.com/images/media/event/thumb/lmblmb1689062500.jpg",
            strBanner:
                "https://www.thesportsdb.com/images/media/event/banner/8uorth1689062943.jpg",
            strMap: null,
            strTweet1: "",
            strTweet2: "",
            strTweet3: "",
            strVideo: "https://www.youtube.com/watch?v=n1_urbVIX2M",
            strStatus: "Match Finished",
            strPostponed: "no",
            strLocked: "unlocked",
        },
        {
            idEvent: "2150530",
            idAPIfootball: "1299338",
            strEvent: "Chelsea vs Noah",
            strEventAlternate: "Noah @ Chelsea",
            strFilename: "UEFA Conference League 2024-11-07 Chelsea vs Noah",
            strSport: "Soccer",
            idLeague: "5071",
            strLeague: "UEFA Conference League",
            strLeagueBadge:
                "https://www.thesportsdb.com/images/media/league/badge/ymfo5j1718775759.png",
            strSeason: "2024-2025",
            strDescriptionEN: "",
            strHomeTeam: "Chelsea",
            strAwayTeam: "Noah",
            intHomeScore: "8",
            intRound: "3",
            intAwayScore: "0",
            intSpectators: null,
            strOfficial: "",
            strTimestamp: "2024-11-07T20:00:00",
            dateEvent: "2024-11-07",
            dateEventLocal: "2024-11-07",
            strTime: "20:00:00",
            strTimeLocal: "20:00:00",
            strGroup: "",
            idHomeTeam: "133610",
            strHomeTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/yvwvtu1448813215.png",
            idAwayTeam: "137895",
            strAwayTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/qylmss1720503567.png",
            intScore: null,
            intScoreVotes: null,
            strResult: "",
            idVenue: "16126",
            strVenue: "Stamford Bridge",
            strCountry: "England",
            strCity: "",
            strPoster: "",
            strSquare: "",
            strFanart: null,
            strThumb:
                "https://www.thesportsdb.com/images/media/event/thumb/vc5sj91725264703.jpg",
            strBanner: "",
            strMap: null,
            strTweet1: "",
            strTweet2: "",
            strTweet3: "",
            strVideo: "https://www.youtube.com/watch?v=9I1JbxuFzZM",
            strStatus: "Match Finished",
            strPostponed: "no",
            strLocked: "unlocked",
        },
    ],
};
